In [1]:
from classification import logistic_regression as lg

In [2]:
lg.hello()

Hello World


In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
X = data.iloc[:, :8]

In [6]:
X.shape

(768, 8)

In [7]:
Y = data.iloc[:, 8:]

In [8]:
Y.shape

(768, 1)

In [9]:
import numpy as np

In [10]:
x = np.array(X)
y = np.array(Y)

In [11]:
rows, columns = x.shape

In [12]:
columns

8

In [13]:
w = np.ones([columns, 1])
b = 1
alpha = 0.1
iters = 100

In [14]:
w.shape

(8, 1)

In [15]:
lg.gradient_descent(x, y, w, b, alpha, iters)

accuracy is : 65.10416666666666
Iteration 0: Cost = nan
accuracy is : 34.89583333333333
Iteration 10: Cost = nan
accuracy is : 65.10416666666666
Iteration 20: Cost = nan
accuracy is : 48.17708333333333
Iteration 30: Cost = nan
accuracy is : 65.10416666666666
Iteration 40: Cost = nan
accuracy is : 54.817708333333336
Iteration 50: Cost = nan
accuracy is : 67.31770833333334
Iteration 60: Cost = nan
accuracy is : 65.10416666666666
Iteration 70: Cost = nan
accuracy is : 35.67708333333333
Iteration 80: Cost = nan
accuracy is : 64.453125
Iteration 90: Cost = nan


/home/Icon0fs1n/libLearn/libLearn/classification/logistic_regression.py:18: RuntimeWarning: overflow encountered in exp
  value = (1 / (1 + np.exp(-z))).round(2)
/home/Icon0fs1n/libLearn/libLearn/classification/logistic_regression.py:27: RuntimeWarning: divide by zero encountered in log
  loss = y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
/home/Icon0fs1n/libLearn/libLearn/classification/logistic_regression.py:27: RuntimeWarning: invalid value encountered in multiply
  loss = y * np.log(predictions) + (1 - y) * np.log(1 - predictions)


(array([[  2.85002474],
        [ -0.41851302],
        [-10.08770964],
        [ -1.27338542],
        [ -3.47770703],
        [ -1.02223659],
        [  1.04500641],
        [ -0.0575612 ]]),
 np.float64(0.58372265625))

In [16]:
w

array([[  2.85002474],
       [ -0.41851302],
       [-10.08770964],
       [ -1.27338542],
       [ -3.47770703],
       [ -1.02223659],
       [  1.04500641],
       [ -0.0575612 ]])

In [17]:
lg.compute_cost(x, y, w, 0.58372265625 )

accuracy is : 65.10416666666666


np.float64(nan)

In [18]:
lg.compute_cost(x, y, w, b)

accuracy is : 65.10416666666666


np.float64(nan)

In [19]:
x.dot(w).shape

(768, 1)

In [20]:
d = np.array([2.212, 3.2324, 5.2323])
d.round(2)

array([2.21, 3.23, 5.23])

In [21]:
import numpy as np

In [22]:
g = np.ones([2, 4])
h = np.zeros([1, 4])
h = h+3
np.dot(g, h.T)

array([[12.],
       [12.]])

In [23]:
g[:, 1]

array([1., 1.])

In [24]:
g[:, 3]

array([1., 1.])

In [25]:
g[1, :]

array([1., 1., 1., 1.])

In [26]:
from regression import nvariate_polynomial_regression as pr
import numpy as np

In [27]:
w = np.arange(9)
w = w.reshape([3, 3])
w = w+1

In [28]:
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
wp = pr.create_polynomial_features(w, 2)

In [30]:
wp.shape

(3, 10)

In [31]:
wp

array([[ 1.,  1.,  2.,  3.,  1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5.,  6., 16., 20., 24., 25., 30., 36.],
       [ 1.,  7.,  8.,  9., 49., 56., 63., 64., 72., 81.]])

In [2]:
[] + [3] + [4]

[3, 4]